--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sameed/Pictures/wallpapers/LegionGoFuturistic.jpg"

-- Special
background="#120d15"
foreground="#d8ccd6"
cursor="#d8ccd6"

-- Colors
color0="#120d15"
color1="#A7445A"
color2="#314F8E"
color3="#5C6895"
color4="#A1778D"
color5="#7289BB"
color6="#A291A6"
color7="#d8ccd6"
color8="#978e95"
color9="#A7445A"
color10="#314F8E"
color11="#5C6895"
color12="#A1778D"
color13="#7289BB"
color14="#A291A6"
color15="#d8ccd6"
