# Shell variables
# Generated by 'wal'
wallpaper='/home/sameed/Pictures/wallpapers/LegionGoFuturistic.jpg'

# Special
background='#120d15'
foreground='#d8ccd6'
cursor='#d8ccd6'

# Colors
color0='#120d15'
color1='#A7445A'
color2='#314F8E'
color3='#5C6895'
color4='#A1778D'
color5='#7289BB'
color6='#A291A6'
color7='#d8ccd6'
color8='#978e95'
color9='#A7445A'
color10='#314F8E'
color11='#5C6895'
color12='#A1778D'
color13='#7289BB'
color14='#A291A6'
color15='#d8ccd6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
